### PR TITLE
Added license and simple setup.py

### PR DESCRIPTION
**Pull request by lextoumbourou**
Hi @borntyping,

As per issues #2 and a discussion in issue #1, I've added a simple ``setup.py`` file (which includes PyTest stuff: ``python setup.py test``) and an MIT license (based on the license your past projects suggest you prefer) to save you the trouble. Hope that's cool. If you would prefer to add the license yourself, let me know and I'll remove it from the PR.

Also, would you like me to hook up a simple Travis conf?

Lex

### CODE REVIEW

**Comment by borntyping** [comment]
A travis conf would be useful, though I'd prefer to set up testing in the same way as my other projects (using tox to run tests and have travis call that - examples: [tox.ini](https://github.com/borntyping/clack/blob/master/tox.ini), [.travis.yml](https://github.com/borntyping/clack/blob/master/.travis.yml).

**Comment by borntyping** [comment]
I'll probably also rename the package to ``csdl-unoffical`` or similar when registering it to PyPI (the module name would stay the same).

**Comment by borntyping** [comment]
I'll finish off anything that needs doing tomorrow morning - thanks for the PR :)

**Comment by lextoumbourou** [comment]
Aight mate. I've added a super simple Tox conf, a Travis conf and removed the PyTest stuffs from ``setup.py``. I'll leave any further customisations to you.

Have a great weekend.

**Comment by borntyping** [comment]
Thanks :)

**Pull request merged**
