### PR TITLE
Add a Group class to allow grouping of statements.

### PR DESCRIPTION
**Pull request by dpnova**
This basically translates to adding a (  and  ) around
statements that need to be grouped.

Would appreciate any thoughts here @lextoumbourou and @borntyping 

I'll be adding lots more targets in the coming months.. so this is just the start. I'd like to know if I'm heading in the right direction.

Cheers!

### CODE REVIEW

**Comment by dpnova** [comment]
Ah.. I haven't added tests. Will do that :)

**Comment by borntyping** [comment]
Thoughts:

- Are you able to rebase/redo this on top of the current master? (Most notably, I moved the targets configuration into it's own file, though there were various other small changes - ffb96b894d93dfcf97da637cd1e9020b6428341a..434b19b90539ed1209535a8428a2f50251d4bfd9)
- The `Statement` class probably shouldn't have functions added to it? (IIRC, it should only be used directly for a 'final' statment - wishing I'd documented this better when I wrote it!)
- Tests and/or examples would be useful - I'm not quite clear on the difference between `Conditional` and `Group`, and I'm not sure how much functionality they share (Again, mostly my fault for being somewhat unfamiliar with the codebase!)

Let me know if there's anything I can help with - if I get the chance I'll start adding a bit more documentation to the code. :smiley:

**Comment by borntyping** [comment]
I'd also be really interested in hearing what people are using this for - this started off as a hackday project while I was working at DataSift, so wasn't really expecting people to start using it :)

**Comment by dpnova** [comment]
Sorry about the rebase foo. I'll sort that out.

I'll be honest and say I interpreted Statement differently when I was reading the code. Basically I ended up arriving at the slightly false conclusion that a statement was more like an expression and could be joined with other statements.

I've very happy to switch it up however required.

As for grouping, Condition currently doesnt really support grouping like this:

    (foo.title contains_any "a,b,c" OR foo.content contains_any "d,e,f") AND NOT (foo.title contains_any "other" or foo.content contains_any 'baz")

The explicit addition of parens makes precedence more explicit and controlled.

As for what we're using it for.. we're doing b2b analytics for the fashion industry.. MVP will be up in the next couple of weeks. Basically users can define their own rules about filtering content which gets applied to DS streams as well as our own index of content.

Cheers!

**Comment by dpnova** [comment]
As an example of how we're using `Group`:

```python
def create_channel_csdl(keywords, included=None, excluded=None):
    """Create the channel CSDL using the right fields."""
    keywords = [k.encode("utf8") for k in keywords]
    included = [k.encode("utf8") for k in included or []]
    excluded = [k.encode("utf8") for k in excluded or []]
    result = Group(
        interaction.raw_content.contains_any(keywords) |
        interaction.hashtags.contains_any(keywords) |
        interaction.title.contains_any(keywords) |
        interaction.author.name.contains_any(keywords) |
        interaction.author.username.contains_any(keywords) |
        links.url.contains_any(keywords) |
        links.domain.contains_any(keywords)
    )
    if included:
        result = result & Group(
            interaction.raw_content.contains_any(included) |
            interaction.hashtags.contains_any(included) |
            interaction.title.contains_any(included) |
            interaction.author.name.contains_any(included) |
            interaction.author.username.contains_any(included) |
            links.url.contains_any(included) |
            links.domain.contains_any(included)
        )
    if excluded:
        result = result & Group(
            interaction.raw_content.contains_any(excluded) |
            interaction.hashtags.contains_any(excluded) |
            interaction.title.contains_any(excluded) |
            interaction.author.name.contains_any(excluded) |
            interaction.author.username.contains_any(excluded) |
            links.url.contains_any(excluded) |
            links.domain.contains_any(excluded)
        ).not_()
    return result
```

**Comment by dpnova** [comment]
OK, looking better against master. Now we can make a call on the methods/statement/group stuff :)

**Comment by borntyping** [comment]
> I'll be honest and say I interpreted Statement differently when I was reading the code. Basically I ended up arriving at the slightly false conclusion that a statement was more like an expression and could be joined with other statements.

It's fine, I'm not so clear on what I originally intended when I wrote the code :smile: On a second reading, I _think_:

- A `Statement` is a CSDL string. It's only returned by the `Condition` class.
- A `Condition` is a target + operator + argument, and so a specific type of statement.
- The `Statement` class is intended to be a valid CSDL string, and never a partially built one (hence the inheritance from `str`).

I think it might make more sense if `Condition` was merged into statement - so any statement could be used with logical operators - and `Group` becomes a function that modifies a statement (or a subclass of `Statement` that does something similar:

```python
def Group(csdl):
    return Statement('({})'.format(csdl))
```

_...or..._

```python
class Group(Statement):
    def __init__(self, csdl):
        super().__init__('({})'.format(csdl))
```

**Comment by borntyping** [comment]
If you're happy with that, I'll merge this PR in the next few days (hopefully sooner rather than later), and finish any of the discussed changes that still need doing. Assuming I have time, I'll also try and make sure the code is somewhat better documented so that it's not so confusing when it comes to making changes :)

**Comment by borntyping** [comment]
I've cleaned up these commits, and they're currently pushed to the [develop](https://github.com/borntyping/python-csdl/commits/develop) branch. This pulls in your changes without the merge commits, and makes a first pass at improving the `Statement`, `Condition` and `Group` classes.

If you've no further comments `develop` will replace `master` - I'll wait before doing any further work bas:smile:

**Comment by borntyping** [comment]
(Accidentally closed the PR when attempting to comment :frowning: )

**Comment by borntyping** [comment]
Also - would you mind me using the example `Group` code you provided as a permanent test/example?

**Comment by dpnova** [comment]
I would be :+1:  for making a statement record what went into it. It's partially there conceptually anyway. I've done something like this previously with the "specification" pattern. Though that would mean somewhat inverting things and making the operators classes.. anyway, food for thought.

Cool with using the group code as an example too!

**Comment by borntyping** [comment]
This has been merged into the current master.

**Comment by borntyping** [comment]
Since I've cherry-picked commits from the PR, you may want to make a clean clone of your fork!
```
git pull git://github.com/borntyping/python-csdl.git master -f
git push -f
```

**Comment by dpnova** [comment]
Cheers!

Sorry about my late replies.. we're pushing towards release, so lots going on :)

**Pull request closed without merging**
